version: 2
jobs:
  ##########################################################################
  #  SHARED STEPS
  ##########################################################################
  build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  lint:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn format:check

  ##########################################################################
  #  FRONT SPECIFIC
  ##########################################################################
  front-test-unit:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn client:test:ci
      - run: yarn add codecov && yarn codecov
  front-build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn client:build:prod
      - run:
          name: Copy deployment artifacts to workspace
          command: |
            cp dist/ /tmp/front -r
      - store_artifacts:
          path: /tmp/front
      - persist_to_workspace:
          root: /tmp
          paths:
            - front
  front-deploy:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/deploy
    steps:
      # why rebuild something we already tested, rebuilding invalidates any previous confidence?!
      - attach_workspace:
          at: /tmp
      - run:
          name: Install netlify-cli
          command: yarn global add netlify-cli
      - run:
          name: Deploy app
          command: netlify deploy -d /tmp/front -a $NETLIFY_TOKEN -s $NETLIFY_SITE

  ##########################################################################
  #  BACK SPECIFIC
  ##########################################################################
  back-test-unit:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn server:test:ci
      - run: yarn add codecov && yarn codecov
  back-test-e2e:
    docker:
      - image: circleci/node:8.11
      - image: circleci/postgres:9.6.5
        environment:
          POSTGRES_DB: psqluer
          POSTGRES_USER: psqluer
          POSTGRES_PASSWORD: psqlpassword
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn server:e2e
  back-build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn server:build
      - run:
          name: Copy deployment artifacts to workspace
          command: |
            cp server-dist/ /tmp/back -r
      - store_artifacts:
          path: /tmp/back
      - persist_to_workspace:
          root: /tmp
          paths:
            - back
  back-deploy:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/deploy
    steps:
      # why rebuild something we already tested, rebuilding invalidates any previous confidence?!
      - attach_workspace:
          at: /tmp
      - run:
          name: TODO
          command: echo "TODO"

workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - back-test-unit:
          requires:
            - build
      - back-test-e2e:
          requires:
            - build
      - lint:
          requires:
            - build
      - front-test-unit:
          requires:
            - build
      - front-build:
          requires:
            - build
            - lint
            - front-test-unit
      - back-build:
          requires:
            - build
            - lint
            - back-test-e2e
            - back-test-unit
      - front-deploy:
          requires:
            - back-build
            - front-build
          filters:
            branches:
              only: master
      - back-deploy:
          requires:
            - back-build
            - front-build
          filters:
            branches:
              only: master
