version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run: yarn install
    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
  lint:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn format:check
  test-back-unit:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn server:test:cov
      - run: yarn add codecov && yarn codecov
  test-back-e2e:
    docker:
      - image: circleci/node:8.11
      - image: circleci/postgres:9.6.5
        environment:
          POSTGRES_DB: psqluer
          POSTGRES_USER: psqluer
          POSTGRES_PASSWORD: psqlpassword
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn server:test:e2e

workflows:
  version: 2
  build-test-and-lint:
    jobs:
    - build
    - test-back:
        requires:
        - build
    - test-back-e2e:
        requires:
        - build
    - lint:
        requires:
        - build
