{
 "title": "Dashboard flow",
 "tags": [
  "nestjs",
  "flow-mapper"
 ],
 "time": { "from": "2019-01-06T21:41:37.809Z", "to": "2019-01-06T22:02:27.809Z" },
 "panels": [
  {
   "title": "95th Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, path, method)) * 100\n",
     "legendFormat": "{{ path }} - {{ method }}"
    }
   ]
  },
  {
   "title": "Number of request by endpoints",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count[5m])) by (method, path)",
     "legendFormat": "{{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])) by (path, method) * 100",
     "legendFormat": "{{ path }} - {{ method }}"
    }
   ]
  },
  {
   "title": "Apdex score",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.3\"}[1m])) by (job)\n+\n  sum(rate(http_request_duration_seconds_bucket{le=\"1.5\"}[1m])) by (job)\n) / 2 / sum(rate(http_request_duration_seconds_count[1m])) by (job)"
    }
   ]
  },
  {
   "title": "Median Response Time:",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, path,  method)) * 100\n",
     "legendFormat": "{{ path }} - {{ mehod }}"
    }
   ]
  },
  {
   "title": "400 and 500 errors",
   "type": "graph",
   "gridPos": { "h": 3, "w": 22, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"5.*|4.*\"}[5m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{code=~\"^5..$\"}[1m])) /  sum(increase(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Errors rate"
    }
   ]
  }
 ]
}